<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>gumonji.Common.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\gumonji.Common\gumonji.Common.csproj" />
    <ProjectReference Include="..\gumonji.Server\gumonji.Server.csproj" />
  </ItemGroup>
</Project>
