// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gumonji.Common.DAL;

#nullable disable

namespace gumonji.Common.DAL.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20261004203246_InlineBackdItemComments")]
    partial class InlineBackdItemComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ClockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Consumption")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("CreatedUnixTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EditLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EyeType")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("FavoriteColor")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LastGumolotTime")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LastLoginTime")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSaveGameTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LoginTotalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MarkName")
                        .HasColumnType("BLOB");

                    b.Property<int?>("MoveCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Nickname")
                        .HasColumnType("BLOB");

                    b.Property<int?>("Novice")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PortalServer")
                        .HasColumnType("BLOB");

                    b.Property<int?>("Subtype")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalExchangedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalExchangedMoney")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("backd.Characters", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterEquipment", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Slot");

                    b.ToTable("backd.CharacterEquipment", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterExperience", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Subtype")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Index");

                    b.ToTable("backd.CharacterExperiences", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterExtension", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Line")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("UserId", "Index");

                    b.ToTable("backd.CharacterExtensions", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterItem", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("C6H4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("CaCO3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Comment0")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment1")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment2")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment3")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment4")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment5")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment6")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Comment7")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CreateId")
                        .HasColumnType("BLOB");

                    b.Property<long?>("CreatedGameTime")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FamilyName")
                        .HasColumnType("BLOB");

                    b.Property<uint?>("Fertilizer")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("SiO2")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("StickerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Subtype")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Water")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Slot");

                    b.ToTable("backd.CharacterItems", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterItemParameter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Slot", "Secret", "Index");

                    b.ToTable("backd.CharacterItemParameters", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterParameter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Index");

                    b.ToTable("backd.CharacterParameters", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdHistory", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("backd.Histories", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("NextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("backd.Sequences", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Body")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("PlayedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Style")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SwimmingDistance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WalkingDistance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("zone.Characters", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fertility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subtype")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Slot")
                        .IsUnique();

                    b.ToTable("zone.InventoryItems", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.LoginToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Token");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("LoginTokens", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.Plant", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fertility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subtype")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("ZoneId", "Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ZoneId", "X", "Y")
                        .IsUnique();

                    b.ToTable("zone.Plants", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.TutorialCompletion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TutorialId");

                    b.ToTable("TutorialCompletions");
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Username")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterEquipment", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacter", null)
                        .WithMany("Equipment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterExperience", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacter", null)
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterExtension", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacter", null)
                        .WithMany("Extensions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterItem", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacter", null)
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterItemParameter", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacterItem", null)
                        .WithMany("Parameters")
                        .HasForeignKey("UserId", "Slot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterParameter", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.BackdCharacter", null)
                        .WithMany("Parameters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.Character", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.InventoryItem", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.LoginToken", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.User", "User")
                        .WithMany("LoginTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.Plant", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.TutorialCompletion", b =>
                {
                    b.HasOne("gumonji.Common.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacter", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Experiences");

                    b.Navigation("Extensions");

                    b.Navigation("Items");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.BackdCharacterItem", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("gumonji.Common.DAL.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("LoginTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
